version: 0.2
phases:
  install:
    runtime-versions:
      php: 8.1
  pre_build:
    commands:
      - composer install 
  build:
    commands:
      - phpunit 

  post_build:
    commands:
      - echo "Post-build steps"
artifacts:
  files:
    - '**/*'

  
